name: Install
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run and test
      run: |
           git clone https://github.com/joerowell/WSL-for-fplll.git
           cd WSL-for-fplll
           chmod +x install_g6k.sh
           ./install_g6k.sh
           mamba activate g6k
           cd g6k
           ./full_sieve.py 60 --verbose